version: "3.9"

services:
  persistence:
    image: maumau-persistence
    build:
      context: ./Persistence/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
    container_name: persistence_service
    tty: true

  maumau:
    image: maumau-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    depends_on:
      - persistence
    container_name: maumau_service
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=host.docker.internal:0
    platform:
      linux/amd64