version: "3.9"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: maumau
      POSTGRES_IP: localhost
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  persistence:
    image: maumau-persistence
    build:
      context: ./Persistence/
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"
    environment:
      - FILE_IO_HOST=fileio
      - FILE_IO_PORT=8081
    container_name: persistence_service

  maumau:
    image: maumau-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      - persistence
    container_name: maumau_service
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=host.docker.internal:0
      - FILEIO_SERVICE_HOST=fileio
      - FILEIO_SERVICE_PORT=8081